### PR TITLE
Move notices about source column headers into individual note cards

### PR DESCRIPTION
**Pull request by jonabc**
This PR changes the way that the action functions regarding how notices are added to the target project column regarding which cards come from which source columns.  There is also a general refactoring for testability between api calls and the general application logic.  Due to the action YML not being backwards compatible, this PR will be the first for a new v2 major release.

Prior to this change, a single notice was added to the top of the target project column with a heavyweight message like
```markdown
**DO NOT EDIT**
text text text
- first source column
- second source column
```

Combined with project boards functionality to automatically render links to other project boards as an additional blurb off the bottom of the project board, you could end up with a very very large card at the top of your column that forced you to scroll to see any real content.  The notice card functionality could be turned off and replaced with a user-created card that included a `<!-- mirror-ignore -->` comment that was slimmer, but I think generally this is something that could be improved.

This change turns the single notice into multiple cards, all of which can be turned off or easily customized.

The top-level notice card is controlled with an `automation_notice` flag which replaces the `add_note` flag.  This card now only shows the `**DO NOT EDIT** This column is automatically managed` style notice without any of the additional long form content.  The note includes an html comment that is used to uniquely identify this card - users can customize the card content as much as they'd like so long as the comment is not removed.

There are also new notice cards that can be added at the top of the cards from each source column controlled by a `source_column_notices` flag.  As an example, when this is enabled you might see a layout like:
```
- column 1 notice
- column 1 card
- column 1 card
- column 2 notice
- column 2 card
- column 3 notice
- column 3 card
```

These cards are each identified by an HTML comment `<!-- column-notice: <column id> -->`.  The cards' default content is `The following cards are from the [<source project>'s '<source column>' column](<source column url>)` to match the older format which linked to every source column.  The cards' content can be customized to whatever is desired as long as the HTML comment is kept in place so that the automation can find and identify the card.

### CODE REVIEW

**Comment by jonabc** [comment]
@glortho @veganpolice @rushtonmd :wave: when you get a chance I'd love to get your thoughts on this change as an attempt to make the column mappings and automation notices less obtrusive and more customizable.  Please give a read through the PR body and readme changes and let me know if you have any questions or comments 🙏

**Comment by veganpolice** [comment]
@jonabc thoughts are this is great. Anything we can do to minimize extra noise and claw back precious column space is a big win

**Review by glortho — APPROVED** [review]
LGTM -- curious to see it in action!

**Comment by jonabc** [comment]
cool, lets give this a go

**Pull request merged**
